### ISSUE TITLE
pod 拉不下来，lfs貌似满了

### ISSUE THREAD

**Issue by 2856571872** [Leonard-iOS/PaddleOCR#1]
'
Downloading PaddleOCR.framework/PaddleOCR (44 MB)
Error downloading object: PaddleOCR.framework/PaddleOCR (3c88fcc): Smudge error: Error downloading PaddleOCR.framework/PaddleOCR (3c88fcc191b660f35e12b4dda3e87582c4f93cdb18fe8dbc9976a670a30a7212): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /private/var/folders/7w/zgwzt5bj6zdbfj4zl31whm_80000gn/T/d20210514-58634-1ck0t16/.git/lfs/logs/20210514T095739.747126.log
Use `git lfs logs last` to view the log.
error: 外部过滤器 'git-lfs filter-process' 失败
fatal: PaddleOCR.framework/PaddleOCR：smudge 过滤器 lfs 失败
warning: 克隆成功，但是检出失败。
您可以通过 'git status' 检查哪些已被检出，然后使用命令
'git restore --source=HEAD :/' 重试
'

**Comment by 2856571872** [comment]
有能运行成功的demo么0.0

**Comment by chivalrousleonard** [comment]
是的，Git FLS满了，opencv2太大了，后面我做下兼容使用依赖的方式导入。
Demo已经有了，现在给我限流了上传不了，你加我qq我发给你。

**Comment by 2856571872** [comment]
> opencv2太大了，后面我做下兼容使用依赖的方式导入。
> Demo已经有了，现在给我限流了上传不了，你加我qq我发给你

老哥，加不上啊，问题太刁钻了0.0

**Comment by chivalrousleonard** [comment]
刷新下首页，我上传了微信二维码
