### ISSUE TITLE
undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by fredliu168** [Leonard-iOS/PaddleOCR#2]
undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_OcrData", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_RYPaddleOCR", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture arm64

**Comment by moyusword** [comment]
这个错误是因为没有把framework的二进制文件下载下来，可能是因为git fls超出限额。
二进制文件有点大，需要的话可以call我邮箱moyusword@yeah.net，我发给你替换掉就可以用了

**Comment by fenglongteng** [comment]
> 这个错误是因为没有把framework的二进制文件下载下来，可能是因为git fls超出限额。
> 二进制文件有点大，需要的话可以call我邮箱[moyusword@yeah.net](mailto:moyusword@yeah.net)，我发给你替换掉就可以用了

我也是报了相同的错误。可以分享到网盘吗？非常感谢。

**Comment by moyusword** [comment]
> > 这个错误是因为没有把framework的二进制文件下载下来，可能是因为git fls超出限额。
> > 二进制文件有点大，需要的话可以call我邮箱[moyusword@yeah.net](mailto:moyusword@yeah.net)，我发给你替换掉就可以用了
> 
> 我也是报了相同的错误。可以分享到网盘吗？非常感谢。

我已经更新了文档说明，按照文档说明正确操作可以通过pod install来导入资源
